language: ruby
os:
  - linux
  - osx
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
before_install:
  - if [ ! -e "$HOME/.cargo/bin" ]; then curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y; fi
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup default nightly
cache:
  directories:
    - $HOME/.rvm/gems
    - $HOME/.cargo
    - $HOME/.multirust
addons:
  apt:
    packages:
    - g++-mingw-w64 # For dlltool
