language: ruby
os:
  - linux
  - osx
dist: trusty
rvm:
  - "2.2"
  - "2.3"
  - "2.4"
before_install:
  - if [ ! -e "$HOME/.cargo/bin" ]; then curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y; fi
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup default nightly
install: bundle install --without benchmark
matrix:
  allow_failures:
    - { rvm: "2.4", os: "osx" } # Ruby 2.4 doesn't seem to work on OS X on Travis, but works for me locally
cache:
  directories:
    - $HOME/.rvm/gems
    - $HOME/.cargo
    - $HOME/.multirust
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: pkg/*
  skip_cleanup: true
  on:
    rvm: 2.2
    tags: true
