language: ruby
os:
- linux
- osx
dist: trusty
rvm:
- '2.2'
- '2.3'
- '2.4'
before_install:
- if [ ! -e "$HOME/.cargo/bin" ]; then curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain
  nightly -y; fi
- export PATH="$HOME/.cargo/bin:$PATH"
- rustup default nightly
install: bundle install --without benchmark
before_cache:
- cp -r pkg $HOME
matrix:
  allow_failures:
  - rvm: '2.4'
    os: osx
cache:
  directories:
  - "$HOME/.rvm/gems"
  - "$HOME/.cargo"
  - "$HOME/.multirust"
deploy:
  provider: releases
  api_key:
    secure: iJ7xHcfSun0dCRudOsnj2xJFa3ua23qz58S6Z8z39uIf/boah6Anoxd+hC1WCdnPClTM+Ps++8vauRJDjIUmwKZGaYqDNpARe483okq7e9CLC/hGysJm/kSfgs1Iu9H+847oB5E8PmZUgm2HEdnB2fQSf1uufoxb2izOiKuNkGDj9Yw2BqBw6cv6EAxQsV+atS2Q7MVIJ2HDUvKuuRzTkZu2DSI7nNTwuNhfwqxd5mA1d9YDrNGjrt5eZ9MSR8fdH3kD/bZqkiAFpj2XgTxlj+hE1HRaGXxRCOOAeEhatWaJsFebA2b6YC/1Ai80W1cYR5jE+cK5HkqQHjPKuEM1o6l9LB0gJWPBQYFmQySmoQ8WMhlRA2vm+ZShg6QdW46DHi9bcgonRMNE5/J0sDEFaXmwKXij3n9rGEMmXOn5CJNfhwHnLjXh/nBFEgEWqbpPNIoDiFHpenlu5+nuWTrWkUos0/lhh36rtsRWjJkl2qPhPQRGkoi5mwUC4+obJq8DrOI0IPAYoS+mVhr8oGG4O8q6OEpiLRc5bTHgLFa0vOGUJsSlCp0hnj2/KbfMgRbTGSzDJewb2nC27EaDSP2ZBxQt0DL6bSyBtzmbxVoT2cDd4dx1iyGbhRHvbkB/rfPVQrvRm6Eq8hnNSBsNnstbHOWDgVZMh1h9FLcTfhNE1/8=
  file_glob: true
  file: "$HOME/pkg/*"
  skip_cleanup: true
  on:
    repo: djudd/human-name-rb
    rvm: 2.2
    tags: true
